### ISSUE TITLE
www.ccc-p.de

### ISSUE THREAD

**Issue by niccokunzmann** [Chaostreff-Potsdam/Chaostreff-Potsdam.github.io#17]
http://www.ccc-p.de/ does not redirect to the page but the calendar uses it.
Possible solution: Also add redirect from that domain.

**Comment by cyroxx** [comment]
Why does the calendar use a non-existing domain in the first place? Can that be changed?

**Comment by niccokunzmann** [comment]
Good point, surely. @profemo

**Comment by cyroxx** [comment]
Can this issue be closed?
