### ISSUE TITLE
Update/remove mention of the bridged freenode IRC channel

### ISSUE THREAD

**Issue by fridtjof** [Chaostreff-Potsdam/Chaostreff-Potsdam.github.io#44]
Freenode has been defunct for quite a while now, and anyone not in the loop about what happened since then would be quite confused :)

Is there a new bridged channel (on libera.chat, maybe)?

**Comment by sknebel** [comment]
good point, I thought we had done that with the bridge shutdown (it wasn't really used by an users and led to freenode spam/trolls leaking and was a bit of a pain to update, so we shut it down at some point).

I'm sitting on #ccc-p on libera, but it's literally just me and ChanServ so probably not worth mentioning ;)

PR: #45

**Comment by cyroxx** [comment]
Closed via #45.
