### ISSUE TITLE
CNAME record ccc-p.org

### ISSUE THREAD

**Issue by niccokunzmann** [Chaostreff-Potsdam/Chaostreff-Potsdam.github.io#9]
Es gibt die Webseite ccc-p.de, die auf chaostreff-potsdam.github.io redirectet.
 
Wollen wir das als Domain verwenden?

Umsetzung:
1. Der Eigentümer von ccc-p.de erstellt einen CNAME record, der auf chaostreff-potsdam.github.io zeigt
2. Eine pull request erstellt eine Datei CNAME, in der ccc-p.de steht.

Notiz:
- Alle Links auf chaostreff-potsdam.github.io bleiben valide und werden redirectet.

Weiterer Prozess:
- [ ] klären, ob wir die Domain wollen
- [ ] Umsetzen

**Comment by cyroxx** [comment]
Wir sollten eine Festlegung treffen, welche Domain wir tatsächlich als Haupt-Domain verwenden wollen (.de bzw .org) - da gibt es mMn noch unterschiedliche Meinungen. Die Entscheidung sollten wir auf anderen Kanälen als Github finden.
Sobald dies geklärt ist, können wir alle anderen Domains dahin umleiten und auch den CNAME hier entsprechend anpassen.

/cc @tzwenn

**Comment by ajuvo** [comment]
/chaoscompatibel in jedem falle .org vor .de !

ajuvo

**Comment by tzwenn** [comment]
Für mich ist `.org` der default, ich übertrage nur nachträglich die records alles auf `.de`.
Auch auf dem VServer steht in den Configs auch nur `.org`.

**Comment by tzwenn** [comment]
Zur eigentlichen Issue: CNAME-Records für Rootdomains sind nicht RFC-konform. Wir könnten CNAME-Flattening o.Ä. von Cloudflare nutzen, aber die scheiden für mich aus Dezentralisierungsgründen aus.
Auch serven weitere Subdomains/Records. K.p. wie GitHub damit umgeht.

Aktuelle, einfachere Lösung gerade ist der 301 von HTTP-Server. Dabei würde ich es belassen.
Reopen, if unsatisfied.

**Comment by tzwenn** [comment]
Gibt nun einen CNAME `www.ccc-p.org` auf die GitHub-Seite.
